name: Only manual approval
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
             
      - name: Manual Workflow Approval
        uses: trstringer/manual-approval@v1
        with:
          approvers: steja6872
          secret: ${{ secrets.TOKEN }}
          minimum-approvals: 1 
      

